version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.netbeans.api:org-openide-util
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-modules-projectuiapi-base
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-modules-projectapi
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-swing-outline
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-nodes
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-modules-options-api
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-dialogs
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-util-ui
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-loaders
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-windows
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-modules-editor-lib2
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-modules-editor-lib
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-modules-editor
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-awt
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-filesystems
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-modules-queries
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-util-lookup
    versions:
    - RELEASE122
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
  - dependency-name: org.apache.netbeans.utilities:nbm-maven-plugin
    versions:
    - "4.5"
